# Generated by Django 2.2.3 on 2019-07-23 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='номер заказа')),
                ('product_name', models.TextField(verbose_name='название')),
                ('product_price', models.IntegerField(verbose_name='цена')),
                ('amount', models.IntegerField(verbose_name='количество')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(verbose_name='номер итерации'),
        ),
    ]
